name: mailer server CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  S3_BUCKET_NAME: mailractionsbucket

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test # 테스트 skip

      # 디렉토리 생성
      - name: Make Directory
        run: mkdir -p bundle

      # Jar 파일 복사
      - name: Copy Jar
        run: cp ./build/libs/g25Server.jar ./bundle

      # appspec.yml 파일 복사
      - name: Copy appspec.yml
        run: cp appspec.yml ./bundle

      # script files 복사
      - name: Copy script
        run: cp ./script/*.sh ./bundle


      # application.yml 복사 (from secret at githubactions)
      - name: Decode application.yml
        run: |
          echo "${{ secrets.APP_YML_BASE64 }}" | base64 -d > ./bundle


      - name: Make zip file
        run: zip -r ./mailer.zip ./bundle
        shell: bash


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./mailer.zip s3://$S3_BUCKET_NAME/

      # Deploy
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws deploy create-deployment \
          --application-name g25mailerletsgo \
          --deployment-group-name g25mailer \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=mailractionsbucket,bundleType=zip,key=mailer.zip \
          --region ap-northeast-2
name: mailer server CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  S3_BUCKET_NAME: mailractionsbucket

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test # 테스트 skip

      # 디렉토리 생성
      - name: Make Directory
        run: mkdir -p bundle

      # Jar 파일 복사
      - name: Copy Jar
        run: cp ./build/libs/g25Server.jar ./bundle

      # appspec.yml 파일 복사
      - name: Copy appspec.yml
        run: cp appspec.yml ./bundle

      # script files 복사
      - name: Copy script
        run: cp ./script/*.sh ./bundle


      # application.yml 복사 (from secret at githubactions)
#      - name: Decode application.yml
#        run: |
#          echo "${{ secrets.APP_YML_BASE64 }}" | base64 -d > ./bundle


      - name: Make zip file
        run: zip -r ./mailer.zip ./bundle
        shell: bash


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./mailer.zip s3://$S3_BUCKET_NAME/

      # Deploy
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws deploy create-deployment \
          --application-name g25mailerletsgo \
          --deployment-group-name g25mailer \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=mailractionsbucket,bundleType=zip,key=mailer.zip \
          --region ap-northeast-2
